<?php

namespace proxy;

/**
 * Class ConsoleReader
 * @package proxy
 */
class ConsoleReader extends \Thread {

    /** @var bool $shutdown */
    public $shutdown;

    /** @var \Threaded $buffer */
    public $buffer;

    public function start(int $options = PTHREADS_INHERIT_ALL) {
        $this->buffer = new \Threaded();
        parent::start($options); // TODO: Change the autogenerated stub
    }

    public function kill() {
        parent::kill();
    }

    public function run() {
        $resource = fopen("php://stdin", "r");
        while ($this->shutdown !== true) {
            $commandLine = trim(fgets($resource));
            if ($commandLine != "") {
                $this->buffer[] = $commandLine;
            }
        }
    }

    public function setGarbage() {
        // TODO: Implement setGarbage() method.
    }
}